// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class BackupGuardApiPigeonCodecReader: FlutterStandardReader {
}

private class BackupGuardApiPigeonCodecWriter: FlutterStandardWriter {
}

private class BackupGuardApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BackupGuardApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BackupGuardApiPigeonCodecWriter(data: data)
  }
}

class BackupGuardApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = BackupGuardApiPigeonCodec(readerWriter: BackupGuardApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BackupGuardApi {
  /// Excludes the file or directory at the given [path] from backups.
  ///
  /// On iOS, this sets the `NSURLIsExcludedFromBackupKey` attribute.
  /// On Android, it checks if the path is inside the `no_backup` directory.
  /// Returns true if successful or inherently excluded.
  func excludeFromBackup(path: String) throws -> Bool
  /// Returns the absolute path to the directory that is excluded from backups.
  /// 
  /// On Android, this returns the `no_backup` directory path.
  /// On iOS, this returns a custom `NoBackup` directory under the Application Support folder.
  func getNoBackupFilesDir() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BackupGuardApiSetup {
  static var codec: FlutterStandardMessageCodec { BackupGuardApiPigeonCodec.shared }
  /// Sets up an instance of `BackupGuardApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BackupGuardApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Excludes the file or directory at the given [path] from backups.
    ///
    /// On iOS, this sets the `NSURLIsExcludedFromBackupKey` attribute.
    /// On Android, it checks if the path is inside the `no_backup` directory.
    /// Returns true if successful or inherently excluded.
    let excludeFromBackupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_native_backup_guard_platform_interface.BackupGuardApi.excludeFromBackup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      excludeFromBackupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          let result = try api.excludeFromBackup(path: pathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      excludeFromBackupChannel.setMessageHandler(nil)
    }
    /// Returns the absolute path to the directory that is excluded from backups.
    /// 
    /// On Android, this returns the `no_backup` directory path.
    /// On iOS, this returns a custom `NoBackup` directory under the Application Support folder.
    let getNoBackupFilesDirChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_native_backup_guard_platform_interface.BackupGuardApi.getNoBackupFilesDir\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getNoBackupFilesDirChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getNoBackupFilesDir()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getNoBackupFilesDirChannel.setMessageHandler(nil)
    }
  }
}
